### ISSUE TITLE
Add basic QC

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#42]
As noted in #41 it would probably be useful to do some basic QC using stats that are already, or can easily, be calculated. This will avoid potentially costly or erroring database creation/assigning attempts.

Suggestions:
* Genome length outliers (by Tukey criterion?) - can be done before fit
* Overall distance outliers - between `mash dist` and regression

**Comment by nickjcroucher** [comment]
I think the distance outliers makes sense, because sometimes there’s just a rogue sample from another species that is nevertheless well-assembled – we could have a “—dist-threshold” cutoff perhaps, at ~0.25 (maybe too conservative)? I suppose this would just be the mean of each sample’s distance to all other samples? This would probably make sense both at the database building stage and the querying stage, just so staphs don’t start forming their own strain within the pneumo database, for instance…

Alternatively, we could look at what pathogen.watch has implemented, unless those metrics are species-specific?
