### ISSUE TITLE
Allow assemblies to have separately defined names

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#43]
At the moment (due to the mash interface) samples are referred to by the filename of their assembly, but it would be convenient to be able to give each sample an arbitrary name in the `--r-files` or `--q-files` input:
```
sample1 assemblies/sample1.contigs.fa
```

Easy enough to update the PopPUNK side, but the mash sketch names are always the file name. Two possible ways of doing this I think:
* Create temporary symlinks of the assemblies at their given names. This would best be done inside a tmp directory to avoid any clashes (copying the resulting sketches into the output dir)
* Keep a table of file names to sample names as part of the database. Less hacky but more work.

**Comment by nickjcroucher** [comment]
For a local system, I don’t see a problem with the first option – if anything, have a renamed directory of sequences might be helpful for the user (rather than having to manually look up which FASTA files correspond to which isolates). I don’t know if there’s a loss of flexibility on multi-user systems, or if there are any special characters mash won’t accept as inputs?

**Comment by johnlees** [comment]
Closed in 620aa4a7f63b01c97f8cbd66f7bee1e7d314b2bb
