### ISSUE TITLE
Input dataset size issue

### ISSUE THREAD

**Issue by Nerdobyte** [johnlees/PopPUNK#68]
Hi John,
Firstly, thanks for this, it's been very helpful.

I was trying to run the following on a dataset of 1018 genome assemblies:
`paste <(ls *.agp.fasta) <(ls *.agp.fasta) > reference_list.txt
poppunk --easy-run --r-files reference_list.txt --output lm_example --threads 4 --plot-fit 5 --min-k 13 --full-db`

However, I can only run the program on 965 genome assembly files at once (i.e. in one run). If I run any more files I get the following error:
`Sketchlib backend not availablePopPUNK (POPulation Partitioning Using Nucleotide Kmers)
	(with backend: mash v2.2)
Mode: Creating clusters from assemblies (create_db & fit_model)
Traceback (most recent call last):
  File "/Users/nadiafernandes/anaconda3/bin/poppunk", line 8, in <module>
    sys.exit(main())
  File "/Users/nadiafernandes/anaconda3/lib/python3.6/site-packages/PopPUNK/__main__.py", line 264, in main
    args.threads, args.overwrite)
  File "/Users/nadiafernandes/anaconda3/lib/python3.6/site-packages/PopPUNK/mash.py", line 338, in constructDatabase
    genome_length, max_prob = assembly_qc(sequences, klist, ignoreLengthOutliers) 
  File "/Users/nadiafernandes/anaconda3/lib/python3.6/site-packages/PopPUNK/utils.py", line 450, in assembly_qc
    "\n".join(outliers))
TypeError: sequence item 0: expected str instance, list found` 

I have read within previously raised issues, that PopPUNK can take 10^4 genome assemblies. Hence, I'm not sure I fully understand why I am running into this issue. Each assembly file is 3.7M to 3.9M in size. Any insights you might be able to offer would be helpful. 

Thanks in advance!

**Comment by nickjcroucher** [comment]
Hi - this was a problem that was hopefully fixed in 2d941b7ebf11345acfd847d92b2c0244978dcdb0 - if you use the latest version of the code from the git master branch, this should solve this error. It looks like there may be assemblies with unexpected sizes in your input list, which can be removed if erroneous, tolerated through changing the '--max-a-dist' argument, or included using '--ignore-lengths' and '--estimated-length' arguments, if this is an expected level of variation.

**Comment by johnlees** [comment]
A new release via conda with this update is forthcoming, but is dependent on some other updates, so for now @nickjcroucher's suggestion of cloning the master branch should work. Otherwise you can downgrade to <v2.

If you are able to use >v2, you may want to look at installing `pp-sketchlib` too, which will scale even better than mash.

**Comment by Nerdobyte** [comment]
Thanks for the quick response. Will try cloning the master branch as @nickjcroucher suggested. If not, will try the downgrade.
