### ISSUE TITLE
Make lineage assignment into a model object

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#79]
Move the existing code so that it follows the inheritance structure of the other models.
Changing the command line options to give model type when using `--fit-model` would also make sense.

**Comment by nickjcroucher** [comment]
Since a75cb4f5f5d1f63d96de9b702ff7c3f296d47d02, the lineage assignment code should be in the correct part of the main routines for conversion to a model type. I've put in some comments where there are temporary fixes to allow this which will probably need to be undone (e.g. where there is a model.save() command).
