### ISSUE TITLE
Parallelise distance matrix reshaping

### ISSUE THREAD

**Issue by nickjcroucher** [johnlees/PopPUNK#80]
Probably best done in sketch lib if possible. First attempt within python is here: ab441429c2f74f18872b286d1c50b99cd817b361. Current status = segfault 11.

**Comment by johnlees** [comment]
See also: https://github.com/johnlees/pp-sketchlib/issues/19

**Comment by nickjcroucher** [comment]
Functioning attempt in d4a250e (same results as single threaded version). Performance no improvement on single core with ~550 sequences. Might improve if [i,j] pair calculation multithreaded, but my combinatorial maths has not been up to the task thus far. Or perhaps slices? Happy that a sketchlib-based solution will ultimately be the best, but any minor modifications to this version may help with mash-based runs.

**Comment by johnlees** [comment]
Had a think about this yesterday, and I couldn't think of a way to do it with simple loop parallelisation. The i and j update in each loop creating a dependency between threads, the fundamental problem being that the two data formats being converted between don't loop with the same control function.

So not surprised this is difficult in python too! I've got a more manual version I'm testing [here](https://github.com/johnlees/pp-sketchlib/tree/matrix_transforms) which uses the index conversion trick to initialise each thread correctly. Compiles (and has python bindings so you can use numpy input/output), but haven't tested yet.

I can also add a nearest neighbour per row function so that this can be the input for the lineage clustering mode. Doubly handy as the same thing is needed for pathoSCE

**Comment by nickjcroucher** [comment]
OK, was worried I was missing something very obvious. I agree the scope for any improvement in performance within pure python is probably limited, I'll see if benchmarking some of these changes with large datasets (which is now feasible with the graph-tools change) might make a difference.

**Comment by johnlees** [comment]
Done in https://github.com/johnlees/pp-sketchlib/pull/21. Now need to use this function in the PopPUNK code.
