### ISSUE TITLE
Switch networkx for graph-tool

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#82]
See https://graph-tool.skewed.de/static/doc/index.html

**Comment by nickjcroucher** [comment]
(Very limited) start here: 7260e5025e3422cca7206fb2b348e5d0f451f01b. Slightly fiddly import code in network.py.

**Comment by nickjcroucher** [comment]
Working for main strain assigning functions in 5623a6710236a0535ec08eed0b1841641e1b3dc0.

Networkx version run on SPARC: https://microreact.org/project/9KY6djAvD (easy run took 1m56.113s on 24 threads)
Graph-tools version run on SPARC: https://microreact.org/project/yHmmBSjw3 (easy run took 1m54.125s on 24 threads)

Running detectably faster on only a few hundred genomes.

Only remaining networkx dependence is in the lineage_assignment.

**Comment by nickjcroucher** [comment]
Note that networks now store vertex labels as integers, not strings. Fiddly to remove and extend the network. Will need to check the behaviour with queries being added.

**Comment by johnlees** [comment]
Great!
I think the integer indices may actually be a good thing, as I was beginning to think that this would be better linking with some of the other matrix code. We might need to change the code round a little, but if we keep a list (mapping int -> label in order) together with graph, which we map between at the start and end, it should be ok?

**Comment by nickjcroucher** [comment]
Yep, I think it is probably better, I just can't quite get my head around the way in which nodes are removed/added - e.g. after removal, the remaining are still consecutively labelled, so there needs to be some way of keeping track of what's what. It is possible to associate data with a vertex, but not sure how links are retained in e.g. shrinkage processes.

Another nice feature is that networks can be masked, e.g. for the visualisation code, rather than copied and pruned.

This version seems much faster with the refinement steps for large networks, I think it is definitely a worthwhile change.
