### ISSUE TITLE
Sample required densification?

### ISSUE THREAD

**Issue by cizydorczyk** [johnlees/PopPUNK#89]
Hello,

What does it mean when I get a NOTE message saying "sample required densification"?

I get this note when I try building an _E. coli_ database, setting the sketch size to 1,000,000 (--min-k set to 15, --max-k set to 45). When I use lower sketch sizes (e.g. 100,000), I tend not to get linear fits (--plot-fit option). Even with a sketch size of 1,000,000, my fits aren't perfect, often jumping around the straight line, but are better than if I use lower sketch sizes.

My dataset consists of 3 STs (131, 73, 1193), with 18, 11, and 4 isolates, respectively. Genome size is ~5Mb.

The worst fits occur usually when comparing isolates within the same ST (sometimes isolates from the same patient, very closely related), but also occur between STs on occasion.

As a side note:
Are there guidelines/minimum sample sizes for running PopPunk? I.e. can I run it on a sample size of ~11 isolates (e.g. just my ST-73 isolates?)

**Comment by johnlees** [comment]
Densification will occur when the sketch size =~ number of k-mers in the genome. It means that not every sketch bin has been filled with an observation of a k-mer. It's not necessarily a problem as the densification still allows distances to be calculated, but generally implies that you are reaching the limit of precision from increase the sketch size.

Note that the resolution in terms of mutation density is roughly 1/s, so with s = 1x10^6 for your genomes you'd be able to resolve around ~5 SNPs difference at the closest.

With very close genomes, as you have within an ST, if you do not increase the sketch size to capture this rare diversity there will be no signal to fit to. This is when you can see fits which aren't straight lines, but in this case you should still get a reasonable estimate close to zero for both core and accessory distances.
The overall distance distribution should therefore still be correct in these cases.

Generally PopPUNK is designed to find the *between* ST distances, and create clusters based on this. With sufficient sketch size you can observe within-cluster distances too, and use this for tree-building etc.

There's no lower limit of sample size for estimating distances, but PopPUNK will probably need at least 10-15 samples to have a chance to getting a good clustering fit which you can evaluate (the lowest we've tried it on is 20).
However, you won't be able to create good clusters within your ST-73 isolates due to the above considerations, though with a big sketch size you can find some structure within them.

For doing sub-clustering, e.g. within an ST, we've got a prototype follow on module available here: 
https://github.com/johnlees/PopPIPE

For more information on within-strain/ST clustering using PopPUNK, we described this in the supplementary methods of the manuscript.

**Comment by cizydorczyk** [comment]
Thank you for the information -- very helpful!! I will also look into PopPIPE as suggested, as my ultimate goal is to analyze within-ST variation.

If I may ask a tangential question -- has PopPunk ever been evaluated with "low coverage" sequencing data?

I have recently come across the concept of "low coverage sequencing" in human genetics, and while obviously the implications for bacterial genomes are different, I was wondering how "complete" do the genomes input to PopPunk have to be to achieve roughly ST-level differentiation. I.e. could the pipeline work with genomes sequenced with a coverage/sequencing depth of <10x (likely missing genomic regions)? Or would the results likely be nonsensical and high quality sequencing (e.g. 100x depth/coverage).

Thank you,
Conrad

**Comment by johnlees** [comment]
An interesting question. I think the reason bacterial sequencing is such high coverage is mostly because machines were designed for human genomes and sample multiplexing still gave much more coverage than needed.
From what I recall, 15x coverage is enough to do SNP calling. I don't know about assembly off the top of my head.

As PopPUNK works with k-mers, you just need to be able to differentiate true count from sequence error. Sequence errors are usually 1-2 counts, so ~10x should be ok, but this may be worth looking at through simulation.

pp-sketchlib, which is the part of PopPUNK which counts and compares the k-mers, can work directly with reads, which is what I'd recommend here. There is an automated error filter used, you will want to lower the minimum count based on expected coverage
